# Generated by Django 2.1.4 on 2019-01-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20190108_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='description',
            field=models.CharField(default='Moj mem', max_length=150),
        ),
    ]
