# Generated by Django 2.1.4 on 2019-01-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_meme_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(blank=True, upload_to='memes_pictures'),
        ),
    ]
