# Generated by Django 2.1.4 on 2019-01-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0008_auto_20190115_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='add_date',
        ),
    ]
