# Generated by Django 2.1.4 on 2019-01-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0009_remove_meme_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='add_date',
            field=models.DateField(auto_now=True),
        ),
    ]
