# Generated by Django 2.1.5 on 2019-01-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0012_meme_wating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='wating',
            new_name='waiting',
        ),
    ]
