# Generated by Django 2.1.5 on 2019-01-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0013_auto_20190123_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
