# Generated by Django 2.1.5 on 2019-02-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0014_auto_20190124_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
