# Generated by Django 2.1.5 on 2019-02-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0015_auto_20190220_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='like',
        ),
    ]
