# Generated by Django 2.1.5 on 2019-02-28 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0021_auto_20190228_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 20, 54, 46, 421269)),
        ),
    ]
