# Generated by Django 2.1.5 on 2019-03-06 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0022_auto_20190228_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='dislikes_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meme',
            name='likes_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meme',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 6, 22, 47, 59, 749246)),
        ),
    ]
