# Generated by Django 2.1.5 on 2019-03-06 22:04

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0023_auto_20190306_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 23, 4, 30, 770593)),
        ),
        migrations.AlterField(
            model_name='meme',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meme',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meme',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(1999, 8, 1, 0, 0), null=True),
        ),
    ]
