# Generated by Django 2.1.5 on 2019-03-06 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0024_auto_20190306_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 23, 5, 47, 396811)),
        ),
        migrations.AlterField(
            model_name='meme',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1999, 8, 1, 0, 0), null=True),
        ),
    ]
